### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by multimeric** [ewels/MegaQC#332]
Properly support MySQL properly as a database backend.

## Subtasks
* [ ] Ensure all the database types work with MySQL (see #319)
* [ ] Add MySQL database driver as a dependency "extra" 
* [ ] Create dockerfiles for MySQL (see #319

## Related Issues
* #67
* #319
